"""Procedural architecture in Blender: ONE deterministic building mass
(generated by boolean-subtracting a grid of window cutters from a base box
-- genuine procedural geometry, not a hand-placed model), then several
different ARCHITECTURAL STYLES applied as materials/UV treatment to
IDENTICAL COPIES of that same mesh -- "commitment to the same geometry":
styles differ only in surface treatment, never in the underlying massing,
window grid, or topology. Verified directly (vertex/face counts are
compared across every style copy, not assumed to match).

Must run inside Blender's own Python (bpy is not pip-installable into a
normal interpreter):

    blender --background --python dgs/procedural_architecture_blender.py

Run standalone this way, it renders a side-by-side comparison PNG of all
styles applied to the same base building.
"""

import math
import sys


def clear_scene():
    import bpy
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for block in list(bpy.data.meshes):
        if block.users == 0:
            bpy.data.meshes.remove(block)


def generate_building_mesh(name, width=4.0, depth=3.0, height=8.0,
                            floors=5, bays_x=3, window_w=0.7, window_h=1.1,
                            sill_height=0.9):
    """Deterministic procedural massing: a box with a floors x bays_x grid
    of window recesses boolean-cut into the front (+Y) and back (-Y) faces.
    Same params -> same resulting mesh, verified by direct vertex-count
    comparison in the test suite, not assumed."""
    import bpy

    # NOTE on scale: primitive_cube_add(size=1.0) creates a cube with LOCAL
    # half-extent 0.5 per axis. object.scale multiplies that local geometry,
    # so scale=(width, depth, height) gives world half-extent
    # (width/2, depth/2, height/2) -- i.e. the intended FULL size. Setting
    # scale directly to the half-extent (an earlier bug here) silently built
    # everything at HALF its intended size, and cutters far enough off that
    # the boolean below found zero overlap and cut nothing -- caught by
    # checking the resulting vertex/face count and finding it identical to
    # an untouched cube, not by assuming the boolean worked.
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0, 0, height / 2))
    base = bpy.context.active_object
    base.name = name
    base.scale = (width, depth, height)
    bpy.context.view_layer.update()   # required: the boolean below reads the
                                       # evaluated (post-transform) mesh, and
                                       # a stale depsgraph made it see scale=1

    cutters = []
    floor_h = height / floors
    bay_w = width / bays_x
    for f in range(floors):
        z = f * floor_h + sill_height + window_h / 2
        if z + window_h / 2 > height:
            continue
        for b in range(bays_x):
            x = -width / 2 + (b + 0.5) * bay_w
            for sign, name_suffix in ((1, "front"), (-1, "back")):
                bpy.ops.mesh.primitive_cube_add(
                    size=1.0, location=(x, sign * (depth / 2), z))
                cutter = bpy.context.active_object
                cutter.name = f"cutter_{f}_{b}_{name_suffix}"
                cutter.scale = (window_w, depth * 0.6, window_h)
                cutters.append(cutter)
    bpy.context.view_layer.update()

    bpy.ops.object.select_all(action="DESELECT")
    for c in cutters:
        c.select_set(True)
    bpy.context.view_layer.objects.active = cutters[0]
    bpy.ops.object.join()
    cutter_union = bpy.context.active_object
    cutter_union.name = f"{name}_cutters"

    mod = base.modifiers.new(name="window_cut", type="BOOLEAN")
    mod.operation = "DIFFERENCE"
    mod.solver = "EXACT"
    mod.object = cutter_union
    bpy.context.view_layer.objects.active = base
    bpy.ops.object.modifier_apply(modifier=mod.name)

    bpy.data.objects.remove(cutter_union, do_unlink=True)

    return base


def uv_unwrap(obj):
    import bpy
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="SELECT")
    bpy.ops.uv.smart_project(angle_limit=math.radians(66), island_margin=0.02)
    bpy.ops.object.mode_set(mode="OBJECT")
    return obj.data.uv_layers.active is not None


STYLE_PRESETS = {
    "gothic":     {"color": (0.16, 0.15, 0.14, 1.0), "roughness": 0.85, "metallic": 0.0},
    "modernist":  {"color": (0.55, 0.62, 0.68, 1.0), "roughness": 0.15, "metallic": 0.6},
    "brutalist":  {"color": (0.42, 0.41, 0.39, 1.0), "roughness": 0.95, "metallic": 0.0},
    "classical":  {"color": (0.88, 0.83, 0.72, 1.0), "roughness": 0.55, "metallic": 0.0},
}


def apply_style_material(obj, style_name):
    import bpy
    preset = STYLE_PRESETS[style_name]
    mat = bpy.data.materials.new(name=f"style_{style_name}")
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = preset["color"]
    bsdf.inputs["Roughness"].default_value = preset["roughness"]
    if "Metallic" in bsdf.inputs:
        bsdf.inputs["Metallic"].default_value = preset["metallic"]
    obj.data.materials.clear()
    obj.data.materials.append(mat)
    return mat


def build_style_comparison(styles=("gothic", "modernist", "brutalist", "classical"),
                            spacing=6.0, **building_kwargs):
    """Generate ONE base building, then duplicate it once per style (exact
    mesh-data duplication -- verified elsewhere to have identical vertex
    and face counts), applying only a different material/UV per copy."""
    import bpy

    clear_scene()
    base = generate_building_mesh("building_base", **building_kwargs)
    uv_unwrap(base)
    base_verts = len(base.data.vertices)
    base_faces = len(base.data.polygons)

    copies = []
    for i, style in enumerate(styles):
        obj = base.copy()
        obj.data = base.data.copy()
        obj.name = f"building_{style}"
        obj.location.x = (i - (len(styles) - 1) / 2) * spacing
        bpy.context.collection.objects.link(obj)
        apply_style_material(obj, style)
        copies.append(obj)

    bpy.data.objects.remove(base, do_unlink=True)
    return copies, base_verts, base_faces


def setup_camera_and_lights(width, height, n_buildings, spacing):
    import bpy
    total_width = spacing * n_buildings
    cam_data = bpy.data.cameras.new("cam")
    cam = bpy.data.objects.new("cam", cam_data)
    bpy.context.collection.objects.link(cam)
    cam.location = (0, -total_width * 1.05, height * 0.55)
    cam.rotation_euler = (math.radians(80), 0, 0)
    cam_data.lens = 20
    bpy.context.scene.camera = cam

    sun_data = bpy.data.lights.new("sun", type="SUN")
    sun_data.energy = 3.0
    sun = bpy.data.objects.new("sun", sun_data)
    sun.location = (5, -5, 10)
    sun.rotation_euler = (math.radians(55), 0, math.radians(35))
    bpy.context.collection.objects.link(sun)

    bpy.ops.mesh.primitive_plane_add(size=total_width * 2, location=(0, 0, 0))
    ground = bpy.context.active_object
    ground.name = "ground"
    gmat = bpy.data.materials.new("ground_mat")
    gmat.use_nodes = True
    gmat.node_tree.nodes.get("Principled BSDF").inputs["Base Color"].default_value = (0.3, 0.32, 0.3, 1.0)
    ground.data.materials.append(gmat)


def render_scene(output_path, resolution=(1200, 500)):
    import bpy
    scene = bpy.context.scene
    try:
        scene.render.engine = "BLENDER_EEVEE_NEXT"
    except TypeError:
        scene.render.engine = "BLENDER_EEVEE"
    scene.render.resolution_x, scene.render.resolution_y = resolution
    scene.render.filepath = str(output_path)
    bpy.ops.render.render(write_still=True)


def demo(output_path=None):
    import pathlib
    if output_path is None:
        # __file__ is dgs/procedural_architecture_blender.py -> repo/notebooks/...
        # (Blender's CWD in --background mode is not reliably the repo root,
        # so a relative path silently wrote to Blender's own CWD before --
        # caught by checking WHERE the file actually landed, not assumed.)
        repo_root = pathlib.Path(__file__).resolve().parents[1]
        output_path = repo_root / "notebooks" / "procedural_architecture_styles.png"
    building_kwargs = dict(width=4.0, depth=3.0, height=8.0, floors=5, bays_x=3)
    styles = ("gothic", "modernist", "brutalist", "classical")
    copies, base_verts, base_faces = build_style_comparison(styles=styles, spacing=6.0, **building_kwargs)

    vert_counts = [len(o.data.vertices) for o in copies]
    face_counts = [len(o.data.polygons) for o in copies]
    print(f"base mesh: {base_verts} verts, {base_faces} faces")
    print(f"per-style copies: verts={vert_counts}  faces={face_counts}")
    print(f"all styles share identical geometry: {len(set(vert_counts)) == 1 and len(set(face_counts)) == 1}")

    setup_camera_and_lights(building_kwargs["width"], building_kwargs["height"], len(styles), spacing=6.0)
    render_scene(output_path)
    print(f"rendered to {output_path}")


if __name__ == "__main__":
    demo()
