"""A procedurally-generated tree (SpeedTree-style recursive branching)
simulated as a real MuJoCo physics structure: each branch is a hinge-jointed
rigid body attached at its parent's tip, generated by simple recursion
(spawn n_children sub-branches, each shorter/thinner than its parent by a
fixed decay factor, tilted away from the parent's axis and spread evenly in
azimuth with some random jitter for a natural, non-symmetric look) rather
than a fixed, hand-authored skeleton.

Recursion, not iteration, because the whole point of SpeedTree-style
procedural vegetation is that the SAME branch-generation rule is applied at
every scale -- the recursive function IS the L-system-like production rule,
terminating once max_depth is reached or a branch gets too short to matter.

Each hinge has a spring (stiffness + springref=0) pulling it back toward the
rest pose baked into its `euler` orientation -- the procedurally-generated
fractal shape IS the rest shape, and wind/gravity perturb branches away from
it and let the spring restore them, which is what makes it sway realistically
instead of just going limp or staying rigid.
"""

import numpy as np
import mujoco


def _branch_xml(depth, max_depth, length, radius, tilt_deg, azimuth_deg,
                 length_decay, radius_decay, n_children, branch_tilt_deg,
                 stiffness, damping, rng, id_counter, min_length):
    """Recursively build one branch (and everything growing from its tip) as
    a MuJoCo XML <body> string. Returns "" once max_depth is exceeded or the
    branch has decayed below min_length -- the recursion's base case."""
    if depth > max_depth or length < min_length:
        return ""

    id_counter[0] += 1
    my_id = id_counter[0]

    children_xml = ""
    if depth < max_depth:
        child_length = length * length_decay
        child_radius = radius * radius_decay
        if child_length >= min_length:
            for i in range(n_children):
                child_azimuth = 360.0 * i / n_children + rng.uniform(-18, 18)
                child_tilt = branch_tilt_deg + rng.uniform(-8, 8)
                children_xml += _branch_xml(
                    depth + 1, max_depth, child_length, child_radius,
                    child_tilt, child_azimuth, length_decay, radius_decay,
                    n_children, branch_tilt_deg, stiffness, damping,
                    rng, id_counter, min_length)

    # color: brown trunk near the base, greener toward the branch tips
    green_frac = min(1.0, depth / max_depth)
    rgba = f"{0.45 - 0.25*green_frac:.3f} {0.30 + 0.35*green_frac:.3f} {0.15:.3f} 1"

    return f"""
    <body name="branch_{my_id}_d{depth}" pos="0 0 {length:.5f}" euler="{tilt_deg:.3f} 0 {azimuth_deg:.3f}">
      <joint name="hinge_{my_id}" type="hinge" axis="1 0 0" pos="0 0 0"
             stiffness="{stiffness}" damping="{damping}" springref="0" range="-45 45"/>
      <geom type="capsule" fromto="0 0 0 0 0 {length:.5f}" size="{radius:.5f}" rgba="{rgba}"/>
      {children_xml}
    </body>"""


def build_tree_model(max_depth=5, n_children=2, trunk_length=0.35, trunk_radius=0.025,
                      length_decay=0.72, radius_decay=0.70, branch_tilt_deg=28.0,
                      stiffness=25.0, damping=2.0, min_length=0.01,
                      wind_amplitude=0.0, seed=0):
    """Build the full recursively-generated tree, rooted (welded) to the
    ground, plus a ground plane and lights. wind_amplitude sets the peak
    horizontal wind speed (m/s-ish, via <option wind=.../>, MuJoCo's built-in
    aerodynamic drag on capsule geoms) -- set once at model-build time; for
    a genuinely SWAYING (not just statically-leaning) tree, simulate_tree_sway
    oscillates model.opt.wind at runtime rather than leaving it constant.

    stiffness/damping were tuned empirically, not guessed: at the module's
    original defaults (stiffness=0.015) gravity ALONE (zero wind) caused the
    tree to droop by 0.93m -- almost its entire height -- because the spring
    was far too weak to hold real branch weight up. Checked a stiffness
    sweep directly; stiffness>=20 keeps gravity-only sag under ~0.09m for
    this tree's mass/geometry, matching a real woody branch's stiffness
    rather than a wet noodle's."""
    rng = np.random.default_rng(seed)
    id_counter = [0]

    trunk_body = _branch_xml(
        depth=0, max_depth=max_depth, length=trunk_length, radius=trunk_radius,
        tilt_deg=0.0, azimuth_deg=0.0, length_decay=length_decay, radius_decay=radius_decay,
        n_children=n_children, branch_tilt_deg=branch_tilt_deg,
        stiffness=stiffness, damping=damping, rng=rng, id_counter=id_counter,
        min_length=min_length)

    n_branches = id_counter[0]

    xml = f"""
    <mujoco>
      <option gravity="0 0 -9.80665" density="1.2" viscosity="0.00002" wind="{wind_amplitude} 0 0"/>
      <visual><headlight ambient="0.5 0.5 0.5" diffuse="0.6 0.6 0.6"/></visual>
      <worldbody>
        <light pos="0.5 -0.5 1.5" dir="-0.3 0.3 -1" diffuse="0.85 0.8 0.7"/>
        <light pos="-0.4 -0.6 1.2" dir="0.3 0.4 -0.7" diffuse="0.4 0.4 0.4"/>
        <geom name="ground" type="plane" size="2 2 0.05" pos="0 0 0" rgba="0.25 0.35 0.2 1"/>
        {trunk_body}
      </worldbody>
    </mujoco>
    """
    model = mujoco.MjModel.from_xml_string(xml)
    return model, n_branches


def simulate_tree_sway(t_max=4.0, dt=0.001, wind_amplitude=10.0, wind_freq_hz=0.6,
                        settle_time=0.6, **model_kwargs):
    """Let the tree settle from its procedurally-generated rest pose under
    gravity (settle_time seconds, no wind), then drive an OSCILLATING wind
    (model.opt.wind's x-component set to wind_amplitude*sin(2*pi*f*t) every
    step -- a constant wind just finds a new static equilibrium once damped,
    which looks like a one-time lean, not swaying) and track the outermost
    (deepest-recursion) branch tip to confirm the recursion actually reaches
    the far branches and that they genuinely oscillate (not frozen, not
    exploding)."""
    model, n_branches = build_tree_model(wind_amplitude=0.0, **model_kwargs)
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)

    # track the LAST body created by the recursion -- guaranteed to be one of
    # the deepest (max_depth) branches, since recursion always finishes a
    # subtree (all its children) before returning
    tip_body_id = model.nbody - 1

    n_steps = int(t_max / dt)
    t_hist = np.zeros(n_steps)
    tip_pos_hist = np.zeros((n_steps, 3))
    for i in range(n_steps):
        t = i * dt
        t_hist[i] = t
        if t > settle_time:
            model.opt.wind[0] = wind_amplitude * np.sin(2 * np.pi * wind_freq_hz * (t - settle_time))
        tip_pos_hist[i] = data.xpos[tip_body_id]
        mujoco.mj_step(model, data)

    rest_idx = min(n_steps - 1, int(settle_time / dt))
    rest_pos = tip_pos_hist[rest_idx]     # settled (post-gravity-sag) rest position
    tip_excursion = np.linalg.norm(tip_pos_hist - rest_pos, axis=1)
    return {
        "t": t_hist,
        "tip_pos": tip_pos_hist,
        "tip_excursion": tip_excursion,
        "n_branches": n_branches,
        "final_max_qvel": float(np.max(np.abs(data.qvel))),
        "any_nan": bool(np.any(np.isnan(data.qpos)) or np.any(np.isnan(data.xpos))),
    }


if __name__ == "__main__":
    print("=== Procedurally-generated (recursive) tree, MuJoCo physics, wind sway ===\n")
    result = simulate_tree_sway()
    print(f"branches generated by recursion: {result['n_branches']}")
    print(f"any NaN: {result['any_nan']}")
    print(f"final max |qvel| (should be small -- settled, not exploding): {result['final_max_qvel']:.4f}")
    print(f"tip excursion range: [{result['tip_excursion'].min():.4f}, {result['tip_excursion'].max():.4f}] m")
    for frac in (0.0, 0.25, 0.5, 0.75, 1.0):
        idx = min(len(result["t"]) - 1, int(frac * (len(result["t"]) - 1)))
        print(f"  t={result['t'][idx]:.2f}s  tip_pos={result['tip_pos'][idx]}  "
              f"excursion={result['tip_excursion'][idx]:.4f}")
