import json

NB = "D:/Summer2026/Dispersion-Assisted-GS-Phase-Recovery/phase_retrieval.ipynb"
with open(NB, "r", encoding="utf-8") as f:
    nb = json.load(f)

md_src = [
    "## 70. OUSD(R&E) Alignment, Circuit Analog & Startup Matrix\n",
    "\n",
    "The six red-arrow items from the OUSD(R&E) Critical Technology Areas list map\n",
    "directly to work already in this notebook:\n",
    "\n",
    "| OUSD Area | This Repo | Section |\n",
    "|-----------|-----------|--------|\n",
    "| **FutureG** | RogueGuard: wideband optical rogue-wave monitor for 6G fiber | §61 |\n",
    "| **Trusted AI** | On-device CNN inference, air-gapped RPi CM4, no cloud | §61 |\n",
    "| **Advanced Computing** | FPGA/ARM split, photonic MVM (250 nm / 2 nm GST) | §67 |\n",
    "| **Integrated Sensing & Cyber** | STEAM camera + SEALS Mie/RD scattering | §69, notebooks/ |\n",
    "| **Directed Energy** | Wavefront phase recovery (GS loop) for DE targeting | §1-§55 |\n",
    "| **Human-Machine Interfaces** | Phase image → 2D cell map, interactive arena | §69, game |\n",
    "\n",
    "DoD component-specific mission areas also covered:\n",
    "\n",
    "| DoD Area | Connection |\n",
    "|----------|------------|\n",
    "| Combat Casualty Care | STEAM blood cell differential: RBC/WBC/CTC in 27 ns/cell |\n",
    "| Military Infectious Diseases | SEALS aerosol detection (anthrax, COVID-like particles) |\n",
    "| Emerging Threat Reduction | RogueGuard: optical network integrity, tamper detection |\n",
    "\n",
    "---\n",
    "\n",
    "### Thevenin / Norton Equivalents of the STEAM Optical Circuit\n",
    "\n",
    "Every optical 2-port has a Thevenin and Norton equivalent — same math as circuits:\n",
    "\n",
    "| Circuit | Optical Analog |\n",
    "|---------|---------------|\n",
    "| Voltage source Vth | Laser field amplitude E_laser |\n",
    "| Series impedance Zth | Cavity linewidth 1/(2*pi*delta_nu) |\n",
    "| Short-circuit current In = Vth/Zth | Photon flux (saturated output) |\n",
    "| Resistor R | Absorber/loss element alpha |\n",
    "| Capacitor C | Anomalous dispersion D > 0 (reactive, stores phase) |\n",
    "| Inductor L | Normal dispersion D < 0 (dual reactive) |\n",
    "| Transformer N1:N2 | Beam splitter amplitude ratio sqrt(T):sqrt(1-T) |\n",
    "| Voltage divider | 50:50 beam splitter: E_out = E_in / sqrt(2) |\n",
    "| Op-amp (gain A) | EDFA / Raman amplifier (gain G) |\n",
    "| LC filter H(f) | Dispersive fiber H(nu) = exp(i*pi*D*nu^2) |\n",
    "\n",
    "**Voltage divider as beam splitter:**\n",
    "V_out = V_in * R2/(R1+R2)  ->  E_out = E_in * sqrt(T)\n",
    "Power: I_out^2 * R = P_in * T  (identical transfer function)\n",
    "\n",
    "**Thevenin of a fiber span:**\n",
    "Z_th = Z_0/n  (fiber impedance = free-space 377 Ohm / refractive index)\n",
    "V_th = E_in * exp(i*beta*L)  (accumulated phase, like voltage through inductor)\n",
    "\n",
    "**SPICE netlist:** see code cell below — DC fiber model via LC ladder.\n",
]

code_src = [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec\n",
    "import pandas as pd\n",
    "\n",
    "# ── 1. Thevenin / Norton equivalents of optical elements ─────────────────\n",
    "# Optical impedance Z = E/H = Z0/n  (Z0 = 376.73 Ohm)\n",
    "Z0  = 376.73   # Ohm, free space\n",
    "n_fiber = 1.468  # SMF-28 at 1550 nm\n",
    "n_air   = 1.000\n",
    "Z_fiber = Z0 / n_fiber\n",
    "Z_air   = Z0 / n_air\n",
    "\n",
    "print('Thevenin equivalents of optical elements')\n",
    "print(f'  Z_fiber  = {Z_fiber:.2f} Ohm  (SMF-28, n={n_fiber})')\n",
    "print(f'  Z_air    = {Z_air:.2f} Ohm  (free space)')\n",
    "print(f'  Fresnel R = {((n_fiber-n_air)/(n_fiber+n_air))**2:.4f}'\n",
    "      f'  (fiber/air interface reflectance, like voltage divider mismatch)')\n",
    "\n",
    "# ── 2. Voltage divider = beam splitter ───────────────────────────────────\n",
    "T_vals   = np.linspace(0, 1, 500)   # beam splitter transmittance\n",
    "V_out_T  = np.sqrt(T_vals)           # field amplitude (like voltage divider)\n",
    "V_out_R  = np.sqrt(1 - T_vals)       # reflected port\n",
    "# Voltage divider: V_out = V_in * R2/(R1+R2)\n",
    "# At T=0.5: R1=R2 -> V_out = 0.5 V_in  -> power = 0.25 P_in\n",
    "# But field (amplitude): E_out = sqrt(T)*E_in = 0.707*E_in  -> power = 0.5 P_in CHECK\n",
    "\n",
    "# ── 3. LC ladder model of dispersive fiber (SPICE analog) ────────────────\n",
    "# GVD: d^2 beta/d omega^2 = beta_2  (ps^2/km)\n",
    "# LC ladder: inductance L per unit length ~ group delay\n",
    "#            capacitance C per unit length ~ bandwidth\n",
    "# Transfer function of N-stage LC ladder at frequency f:\n",
    "# H_LC(f) = (1/(1 - (2*pi*f)^2*LC))^N  (low-pass Butterworth-like)\n",
    "# For dispersive fiber: H_fiber(f) = exp(i*pi*D*f^2)\n",
    "# These match when: 2*pi^2*LC = pi*D -> LC = D/2\n",
    "\n",
    "D_fiber = -600e-24   # s^2  (= -600 ps^2, convert to SI)\n",
    "# Choose L = 1 nH, C = D/(2L)\n",
    "L_stage = 1e-9       # H\n",
    "C_stage = abs(D_fiber) / (2 * L_stage)   # F\n",
    "omega_cutoff = 1 / np.sqrt(L_stage * C_stage)   # rad/s\n",
    "f_cutoff = omega_cutoff / (2*np.pi)              # Hz\n",
    "\n",
    "print(f'\\nLC ladder model of D1=-600 ps^2 fiber:')\n",
    "print(f'  L = {L_stage*1e9:.1f} nH  C = {C_stage*1e15:.2f} fF')\n",
    "print(f'  Cutoff frequency = {f_cutoff/1e12:.2f} THz')\n",
    "\n",
    "# Transfer function comparison\n",
    "f_THz = np.linspace(-1, 1, 1000)   # THz\n",
    "nu    = f_THz\n",
    "D_ps2 = -600.0   # ps^2\n",
    "\n",
    "H_fiber = np.exp(1j*np.pi*D_ps2*nu**2)   # exact dispersive fiber\n",
    "# 10-stage LC ladder\n",
    "N_stages = 10\n",
    "omega = 2*np.pi*f_THz * 1e12   # rad/s\n",
    "with np.errstate(invalid='ignore'):\n",
    "    H_lc = (1.0 / (1 - omega**2*L_stage*C_stage + 0j))**N_stages\n",
    "\n",
    "# ── 4. OUSD Startup opportunity matrix ───────────────────────────────────\n",
    "startup_data = {\n",
    "    'Product':   ['RogueGuard',    'STEAM-Dx',      'TS-QPI Module', 'SEALS Sensor'],\n",
    "    'OUSD Area': ['FutureG + AI',  'Integrated Sensing + Combat Care',\n",
    "                  'Directed Energy + HMI', 'Integrated Sensing + BioThreat'],\n",
    "    'Core Tech': ['TD-GS + CNN',   'STEAM + TD-GS', 'Phase retrieval', 'Mie + RD scatter'],\n",
    "    'TAM ($M)':  [420,             1800,             280,              650],\n",
    "    'TRL':       [4,               3,                3,                4],\n",
    "    'DoD Path':  ['SBIR Ph.II',    'SBIR Ph.I -> CDMRP', 'DARPA BAA', 'SBIR Ph.I'],\n",
    "    'Time-to-Rev (yr)': [2.5,      4.0,              3.0,              2.0],\n",
    "}\n",
    "df = pd.DataFrame(startup_data)\n",
    "print('\\n--- OUSD-Aligned Startup Opportunity Matrix ---')\n",
    "print(df.to_string(index=False))\n",
    "\n",
    "# ── 5. Revenue model (SBIR path) ─────────────────────────────────────────\n",
    "# SBIR Phase I: up to $275k  (6 months feasibility)\n",
    "# SBIR Phase II: up to $1.8M (2 years development)\n",
    "# Phase III: commercialization, no SBIR limit\n",
    "sbir_phases = {\n",
    "    'Phase I  (~6 mo)':  275e3,\n",
    "    'Phase II (~2 yr)':  1.8e6,\n",
    "    'Phase III (revenue)': None,\n",
    "}\n",
    "print('\\nSBIR funding path:')\n",
    "for k,v in sbir_phases.items():\n",
    "    val = f'${v/1e6:.2f}M' if v else 'Revenue (no cap)'\n",
    "    print(f'  {k}: {val}')\n",
    "\n",
    "# ── 6. Plot ───────────────────────────────────────────────────────────────\n",
    "fig = plt.figure(figsize=(15, 9))\n",
    "fig.patch.set_facecolor((0.05, 0.05, 0.12))\n",
    "gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.5, wspace=0.4)\n",
    "\n",
    "def dark(ax):\n",
    "    ax.set_facecolor((0.07,0.07,0.15))\n",
    "    for s in ax.spines.values(): s.set_color('gray')\n",
    "    ax.tick_params(colors='white', labelsize=8)\n",
    "    ax.title.set_color('white')\n",
    "    ax.xaxis.label.set_color('white')\n",
    "    ax.yaxis.label.set_color('white')\n",
    "\n",
    "# A: Beam splitter voltage divider analogy\n",
    "ax0 = fig.add_subplot(gs[0, 0])\n",
    "ax0.plot(T_vals, V_out_T**2, color='gold',        lw=2, label='Transmitted P = T*Pin')\n",
    "ax0.plot(T_vals, V_out_R**2, color='cornflowerblue', lw=2, label='Reflected P = (1-T)*Pin')\n",
    "ax0.axvline(0.5, color='gray', lw=1, ls='--', label='50:50 splitter')\n",
    "ax0.set_xlabel('Transmittance T', fontsize=9)\n",
    "ax0.set_ylabel('Power fraction', fontsize=9)\n",
    "ax0.set_title('Beam Splitter = Voltage Divider\\nP = T*Pin  (field: E=sqrt(T)*Ein)', fontweight='bold', fontsize=9)\n",
    "ax0.legend(fontsize=7); dark(ax0)\n",
    "\n",
    "# B: LC ladder vs exact fiber H(f) magnitude\n",
    "ax1 = fig.add_subplot(gs[0, 1])\n",
    "ax1.plot(f_THz, np.abs(H_fiber), color='white',    lw=2,   label='Exact |H_fiber|=1')\n",
    "ax1.plot(f_THz, np.abs(H_lc),   color='tomato',    lw=1.5, label=f'LC ladder N={N_stages}', ls='--')\n",
    "ax1.set_xlabel('Frequency [THz]', fontsize=9)\n",
    "ax1.set_ylabel('|H(f)|', fontsize=9)\n",
    "ax1.set_title('Fiber H(f) vs LC Ladder (SPICE)\\nExact: |H|=1 for all f (lossless)', fontweight='bold', fontsize=9)\n",
    "ax1.set_ylim(0, 1.5); ax1.legend(fontsize=7); dark(ax1)\n",
    "\n",
    "# C: phase response comparison\n",
    "ax2 = fig.add_subplot(gs[0, 2])\n",
    "ax2.plot(f_THz, np.angle(H_fiber)/np.pi, color='white',  lw=2,   label='Fiber phase/pi')\n",
    "ax2.plot(f_THz, np.angle(H_lc)/np.pi,   color='tomato',  lw=1.5, label='LC phase/pi', ls='--')\n",
    "ax2.set_xlabel('Frequency [THz]', fontsize=9)\n",
    "ax2.set_ylabel('Phase / pi [rad/pi]', fontsize=9)\n",
    "ax2.set_title('Phase Response: Fiber vs LC SPICE\\nQuadratic (fiber) vs rational (LC)',\n",
    "              fontweight='bold', fontsize=9)\n",
    "ax2.legend(fontsize=7); dark(ax2)\n",
    "\n",
    "# D: TAM bubble chart\n",
    "ax3 = fig.add_subplot(gs[1, 0:2])\n",
    "colors_p = ['#ff3278','#50d0ff','#ffd040','#00ff9f']\n",
    "for i, row in df.iterrows():\n",
    "    ax3.scatter(row['Time-to-Rev (yr)'], row['TAM ($M)'],\n",
    "                s=row['TRL']*200, color=colors_p[i], alpha=0.85, zorder=3)\n",
    "    ax3.annotate(row['Product'],\n",
    "                 (row['Time-to-Rev (yr)'], row['TAM ($M)']),\n",
    "                 textcoords='offset points', xytext=(8,4),\n",
    "                 fontsize=9, color=colors_p[i], fontweight='bold')\n",
    "ax3.set_xlabel('Time to Revenue [years]', fontsize=9)\n",
    "ax3.set_ylabel('TAM [$M]', fontsize=9)\n",
    "ax3.set_title('OUSD-Aligned Startup Opportunities\\n'\n",
    "              'Bubble size = TRL (1-9)  |  SBIR Phase I -> II path',\n",
    "              fontweight='bold', fontsize=10)\n",
    "ax3.set_xlim(1, 5); ax3.set_ylim(0, 2200)\n",
    "# SBIR funding milestones\n",
    "ax3.axhline(y=0, color='gray', lw=0.5, ls=':')\n",
    "dark(ax3)\n",
    "\n",
    "# E: OUSD checklist (the red arrows)\n",
    "ax4 = fig.add_subplot(gs[1, 2])\n",
    "ax4.axis('off'); ax4.set_facecolor((0.07,0.07,0.15))\n",
    "ousd_items = [\n",
    "    ('--> FutureG',                    '#ff3278',  'RogueGuard fiber monitor'),\n",
    "    ('--> Trusted AI & Autonomy',      '#ffd040',  'On-device CNN, air-gapped'),\n",
    "    ('    Biotechnology',              '#445566',  '(STEAM-Dx stretch goal)'),\n",
    "    ('--> Advanced Computing',         '#50d0ff',  'Photonic MVM, FPGA/ARM'),\n",
    "    ('--> Integrated Sensing & Cyber', '#00ff9f',  'STEAM + SEALS'),\n",
    "    ('--> Directed Energy',            '#ff8040',  'Wavefront / GS phase recovery'),\n",
    "    ('    Hypersonics',                '#445566',  ''),\n",
    "    ('    Microelectronics',           '#445566',  '(photonic IC path)'),\n",
    "    ('    Quantum Science',            '#445566',  ''),\n",
    "    ('--> Human-Machine Interfaces',   '#cc88ff',  'Phase image + arena UI'),\n",
    "]\n",
    "for i,(label, col, note) in enumerate(ousd_items):\n",
    "    y = 0.95 - i*0.095\n",
    "    ax4.text(0.02, y, label, transform=ax4.transAxes,\n",
    "             fontsize=8.5, color=col, fontweight='bold' if '-->' in label else 'normal',\n",
    "             fontfamily='monospace')\n",
    "    if note:\n",
    "        ax4.text(0.58, y, note, transform=ax4.transAxes,\n",
    "                 fontsize=7.5, color='gray', style='italic')\n",
    "ax4.set_title('OUSD R&E Critical Areas\\n(arrows = this repo)', color='white',\n",
    "              fontsize=9, fontweight='bold')\n",
    "\n",
    "fig.suptitle(\n",
    "    'Sec 70: OUSD(R&E) Alignment  |  Thevenin/Norton Optical Circuit Analog  |  STEAM Startup Matrix',\n",
    "    color='white', fontsize=11, fontweight='bold', y=1.01\n",
    ")\n",
    "plt.savefig('references/pptx_figures/ousd_alignment.png',\n",
    "            dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())\n",
    "plt.show()\n",
    "print('Saved: references/pptx_figures/ousd_alignment.png')\n",
    "\n",
    "# ── SPICE netlist (printed, not simulated — use LTspice / ngspice) ────────\n",
    "spice_netlist = '''\n",
    "* STEAM Camera Optical Circuit — Thevenin analog\n",
    "* Run in LTspice or ngspice\n",
    "*\n",
    "* Laser (Thevenin: pulse source + cavity impedance)\n",
    "Vlaser  IN  0   PULSE(0 1 0 0.1p 0.1p 2n 10n)  ; 100 fs pulse, 100 MHz rep\n",
    "Zlaser  IN  N1  {Z0/n_fiber}                     ; cavity output impedance\n",
    "*\n",
    "* DCF1: D1=-600 ps^2  (10-stage LC ladder, each stage = 60 ps^2)\n",
    "L1a N1  N1b 0.3n   ; GVD inductor\n",
    "C1a N1b 0   20f    ; bandwidth cap\n",
    "L1b N1b N1c 0.3n\n",
    "C1b N1c 0   20f\n",
    "* ... (repeat 10x for full 600 ps^2)\n",
    "*\n",
    "* Cell (phase object: reactive load = capacitor for phase delay)\n",
    "Ccell N1c N2 {C_cell}  ; phase shift = arctan(omega*Z*C_cell)\n",
    "*\n",
    "* DCF2: D2-D1=-600 ps^2  (matched 10-stage LC)\n",
    "L2a N2  N2b 0.3n\n",
    "C2a N2b 0   20f\n",
    "* ...\n",
    "*\n",
    "* Photodetector (matched termination)\n",
    "Rdet N_out 0 {Z0/n_fiber}  ; I(Rdet)^2 * R = optical power\n",
    "*\n",
    ".param Z0=376.73 n_fiber=1.468 C_cell=50f\n",
    ".tran 0.01p 5n\n",
    ".measure tran Vpeak MAX V(N_out)\n",
    ".end\n",
    "'''\n",
    "print('\\n--- SPICE Netlist (STEAM Camera Optical Circuit) ---')\n",
    "print(spice_netlist)\n",
    "# Write netlist to file\n",
    "with open('references/steam_camera.cir', 'w') as f:\n",
    "    f.write(spice_netlist)\n",
    "print('Written to references/steam_camera.cir  (open in LTspice / ngspice)')\n",
]

md_cell   = {"cell_type": "markdown", "metadata": {}, "source": md_src}
code_cell = {"cell_type": "code",     "execution_count": None,
             "metadata": {},          "outputs": [], "source": code_src}

nb["cells"].append(md_cell)
nb["cells"].append(code_cell)

with open(NB, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Done. Notebook now has {len(nb['cells'])} cells.")
