"""Score the repo's untracked files by theme relevance -> REPO_INVENTORY.md.

Non-destructive cleanup aid: ranks every untracked file against the
dispersion-assisted project theme (via manifesto_vector) so the loose sprawl
can be triaged -- keep / review / likely-stray -- without deleting anything.
"""
import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
from dgs import manifesto_vector as mv

ROOT = pathlib.Path(__file__).resolve().parents[1]

untracked = subprocess.run(
    ["git", "status", "--porcelain", "--untracked-files=all"],
    cwd=ROOT, capture_output=True, text=True).stdout.splitlines()
files = [ln[3:].strip() for ln in untracked if ln.startswith("??")]
files = [f for f in files if pathlib.Path(f).suffix in (".py", ".ipynb", ".md", ".txt", ".v", ".vhd", ".json")]

rows = []
for f in sorted(files):
    score, cons = mv.score_file(ROOT / f)
    rows.append((score, f, cons))
rows.sort(key=lambda r: -r[0])

KEEP, REVIEW = 0.40, 0.20
def bucket(s):
    return "keep" if s >= KEEP else "review" if s >= REVIEW else "likely-stray"

lines = ["# Repo inventory — untracked files by theme relevance",
         "",
         "Auto-generated by `scripts/build_repo_inventory.py` (torch concept-vector vs the",
         "dispersion-assisted GS project theme). **Nothing is deleted** — this is triage only.",
         "",
         f"- **keep** (≥{KEEP:.2f}): on-topic, belongs in the repo",
         f"- **review** ({REVIEW:.2f}–{KEEP:.2f}): tangential — confirm before committing",
         f"- **likely-stray** (<{REVIEW:.2f}): probably scratch/off-topic — candidate to move or drop",
         "",
         "| relevance | bucket | file | concepts |",
         "|----------:|--------|------|----------|"]
for score, f, cons in rows:
    lines.append(f"| {score:.3f} | {bucket(score)} | `{f}` | {', '.join(cons[:4])} |")

n_keep = sum(1 for s, _, _ in rows if s >= KEEP)
n_rev = sum(1 for s, _, _ in rows if REVIEW <= s < KEEP)
n_stray = sum(1 for s, _, _ in rows if s < REVIEW)
lines += ["", f"**Totals:** {len(rows)} files — {n_keep} keep, {n_rev} review, {n_stray} likely-stray."]

out = ROOT / "REPO_INVENTORY.md"
out.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {out.name}: {len(rows)} files ({n_keep} keep / {n_rev} review / {n_stray} stray)")
